### ISSUE TITLE
Fix deployment of the ROCC to EC2

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/rocc-app#141]
I can dockerize and start the app on the EC2, however the app is facing the CORS issue:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://rocc-alb-69247200.us-east-1.elb.amazonaws.com:80/api/v1/tags. (Reason: CORS request did not succeed).
```

Using the following configuration in `.env`:

```
## SERVER
SERVER_PROTOCOL=https://
SERVER_DOMAIN=rocc-alb-69247200.us-east-1.elb.amazonaws.com
SERVER_PORT=80
SERVER_BASE_PATH=/api/v1
```

I think that the issue is the `:80` that is included in the API url that the app use. Removing the token `:80` may solve the issue.

**Comment by tschaffter** [comment]
@rrchai Is there a reason you are overwriting the environment file with `src/environments/setenv.ts` instead of having the environment file reading configuration from env vars?

**Comment by rrchai** [comment]
@tschaffter I haven't really tried what would happen if I just read `.env` in the `environments.ts`, but according this [article](https://javascript.plainenglish.io/setup-dotenv-to-access-environment-variables-in-angular-9-f06c6ffb86c0) I referred:
>the Angular compiler treats these environment.*.ts files as static, and it wouldn’t compile.

Just curious, have you tried `SERVER_DOMAIN=localhost`? I thought the `localhost` in the `SERVER_DOMAIN` is actually the ip address of server container using `nginx`.

**Comment by tschaffter** [comment]
> Just curious, have you tried SERVER_DOMAIN=localhost?

Yes but it does not work. The important element to consider is that the web client is an app that is run on the computer of the user. In the case where the API url includes "localhost", localhost will refer to the computer of the user. This is why `SERVER_DOMAIN` must be set to the domain name of the server running the app and API service.

**Comment by tschaffter** [comment]
Depends on #143

**Comment by tschaffter** [comment]
Done, the app is now up and running on an EC2.
