### ISSUE TITLE
The avatar of users created using the sign up form does not render properly

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/rocc-app#207]
The "letters" avatar must be used if `user.avatarUrl` is `undefined` OR empty.

![image](https://user-images.githubusercontent.com/3056480/132927479-a3d1e54d-66bc-4864-b97c-14d31771f702.png)

**Comment by rrchai** [comment]
The issue is because the `name` property is missing for the new user created from sign-up, e.g 
```
    {
      "createdAt": "2021-09-14T14:27:12.772000Z",
      "email": "awesome-use222r@example.org",
      "id": "6140e980b595ee1cee9f1d71",
      "login": "awesome-user222",
      "type": "User",
      "updatedAt": "2021-09-14T14:27:12.772000Z"
    }
```
