### ISSUE TITLE
Date pipe does not match the UTC in current challenge page

### ISSUE THREAD

**Issue by rrchai** [Sage-Bionetworks/rocc-app#225]
"2021-12-31" will be stored as "2021-12-31T00:00:00Z" in database ending with "Z", which represents UTC. Just using  `"2021-12-31T00:00:00Z" | date: "yyyy-MM-dd"` will minus one day and show `2021-12-30`.

**Comment by tschaffter** [comment]
We can create custom Angular pipes if needed. Here are [some](https://github.com/Sage-Bionetworks/sagebio-collaboration-portal/tree/develop/client/components/pipes) I created for another project two years ago.

**Comment by tschaffter** [comment]
@rrchai Is this issue closed?
