### ISSUE TITLE
Add metrics to the home page

### ISSUE THREAD

**Issue by jiaxinmachine88** [Sage-Bionetworks/rocc-app#336]
Per user feedback (see below), we will investigate adding metrics to the Home Page. 
We can start with our current set of past challenges. 

Organizer Feedback 
"So the first thing that I would, I would want to see as I'm seeing that page right now is somewhere indicating the community engagement of this challenge. How many challenges are currently listed in our inventory? How many users are there? How many participants do they follow that? It could be something as simple as underneath the register button with white font on top of the green color mentioning, you know, we're currently have exactly over there. We currently have a list of X challenges, you know, a thousand or 120 challenges we have in our community, 10,000 participants. We have 10 organizers. So what is, so that will show me immediately the level of engagement from the community, with this, with this platform, with this inventory." 

Tasks:

- [ ] Backend - @tschaffter
- [ ] Frontend - @vpchung

**Comment by jiaxinmachine88** [comment]
Assigned to @tschaffter. Including @vpchung due to the Home page dependency on this.

**Comment by tschaffter** [comment]
Implementation:

- [ ] https://github.com/Sage-Bionetworks/rocc-schemas/pull/202
- [ ] Service TBA
- [ ] DB client TBA
- [ ] Client for Angular TBA
- [ ] App TBA

**Comment by tschaffter** [comment]
The new [path ](https://github.com/Sage-Bionetworks/rocc-schemas/blob/277c0811898d3ce778f104e77cfea9194a769532/openapi/openapi.yaml#L92)`/registry` provides the following metrics about the registry:

- number of challenges
- number of users
- number of organizations

This change is implemented at the server level. I'll update the client shortly. I'll update the client shortly and display this numbers on the home page.
