### ISSUE TITLE
Identify the Use Cases

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/rocc-app#4]
Identify the Use Cases of the ROCC and add them to the sheet Use Cases of the document [ROCC Use Cases](https://docs.google.com/spreadsheets/d/13KmkKRJzVYig2WgLNdYqS80IQGYBBt5HCd9UsAncDt4/edit#gid=0).

**Comment by tschaffter** [comment]
@vpchung Do you want to give a first shot to the list of use cases?

**Comment by tschaffter** [comment]
The list of use cases in the sheet "Copy of Use Cases" comes from the Challenge Platform 2.0 project. There may be use cases that we may want to include to the ROCC use cases.

**Comment by vpchung** [comment]
Some use cases are identified in the [Persona profiles](https://docs.google.com/document/d/1ktmhju14teHIrx9gkwZqPNKeLCzOYXIVjE00ODdv760/edit?usp=sharing), but we could potentially expand on it some more.

**Comment by tschaffter** [comment]
I'll take a pass on this document. Then we can validate it and close this ticket.

**Comment by tschaffter** [comment]
Yes

**Comment by vpchung** [comment]
They have been translated over to Google Sheets! Please let me know what you think I could modify/expand on.

**Comment by tschaffter** [comment]
We will update the use cases as we develop the app.
