### ISSUE TITLE
Add starting codebase for portal

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks/rocc-app#6]

**Comment by tschaffter** [comment]
Related to https://github.com/Sage-Bionetworks/rocc/issues/16

I would still like to find the time to complete the Angular tutorial referenced in this ticket. :-)

**Comment by vpchung** [comment]
Continuing from that conversation, the two boilerplates I am following are:

* [react-boilerplate](https://www.reactboilerplate.com/)
* [MDB Angular Boilerplate](https://mdbootstrap.com/freebies/angular/boilerplate/)

**Comment by tschaffter** [comment]
@vpchung After discussing with Verena, we agree that it makes sense to re-use the code base of the SageBio Collaboration Portal (SBCP). This app includes many advanced technologies that will enable us to deliver an impactful ROCC prototype. Examples are:

- Use of webhooks for instant in-app notifications
- Use of existing RxJS pipelines for a reactive app
- Re-use existing Angular components like filters, card/item view
- Support for Google OAuth, SAML (which we will probably not use) and OpenID Connect. We could also add support for Synapse OAuth 2.0 server.

The SBCP repository include the codebase for the frontend (Angular, TypeScript) and the backend (Express, JavaScript). A good practice is two host the frontent and backend in different GitHub repositories, each of them configured to publish a Docker image to Docker Hub.

One decision we need to make is whether we want to re-use the backend server from the SBCP (Express, JavaScript) or if we develop it as a Python-Flask app or if we combine the two? Ideally I would like us to adopt a typed language for the backend (i.e. not JS) for improved security and code robustness. The server technology should also be efficient/quick to answer queries (is Python-Flask suitable). It's probably OK if we don't follow this two ideal requirements for the prototype, i.e. both the JS Express server and Python-Flask would be suitable candidates for a ROCC prototype.

**Comment by tschaffter** [comment]
I created the initial Angular app.

```
$ ng new rocc
? Do you want to enforce stricter type checking and stricter bundle budgets in the workspace?
  This setting helps improve maintainability and catch bugs ahead of time.
  For more information, see https://angular.io/strict Yes
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? SCSS   [ https://sass-lang.com/documentation/syntax#scss                ]
CREATE rocc/README.md (1013 bytes)
CREATE rocc/.editorconfig (274 bytes)
CREATE rocc/.gitignore (631 bytes)
CREATE rocc/angular.json (3689 bytes)
CREATE rocc/package.json (1194 bytes)
CREATE rocc/tsconfig.json (783 bytes)
CREATE rocc/tslint.json (3185 bytes)
CREATE rocc/.browserslistrc (703 bytes)
CREATE rocc/karma.conf.js (1421 bytes)
CREATE rocc/tsconfig.app.json (287 bytes)
CREATE rocc/tsconfig.spec.json (333 bytes)
CREATE rocc/src/favicon.ico (948 bytes)
CREATE rocc/src/index.html (290 bytes)
CREATE rocc/src/main.ts (372 bytes)
CREATE rocc/src/polyfills.ts (2830 bytes)
CREATE rocc/src/styles.scss (80 bytes)
CREATE rocc/src/test.ts (753 bytes)
CREATE rocc/src/assets/.gitkeep (0 bytes)
CREATE rocc/src/environments/environment.prod.ts (51 bytes)
CREATE rocc/src/environments/environment.ts (662 bytes)
CREATE rocc/src/app/app-routing.module.ts (245 bytes)
CREATE rocc/src/app/app.module.ts (393 bytes)
CREATE rocc/src/app/app.component.scss (0 bytes)
CREATE rocc/src/app/app.component.html (25757 bytes)
CREATE rocc/src/app/app.component.spec.ts (1051 bytes)
CREATE rocc/src/app/app.component.ts (209 bytes)
CREATE rocc/e2e/protractor.conf.js (904 bytes)
CREATE rocc/e2e/tsconfig.json (274 bytes)
CREATE rocc/e2e/src/app.e2e-spec.ts (655 bytes)
CREATE rocc/e2e/src/app.po.ts (274 bytes)
✔ Packages installed successfully.
    Directory is already under version control. Skipping initialization of git.
```
