### ISSUE TITLE
Unable to seed Challenge without challengeResults

### ISSUE THREAD

**Issue by rrchai** [Sage-Bionetworks/rocc-app#62]
Based on the [schema](https://github.com/Sage-Bionetworks/rocc-schemas/blob/develop/openapi/components/schemas/ChallengeCreateRequest.yaml), `challengeResults` is not required. However, when we seed challenges, we notice that if we do create a challenge request without `challengeResults`, it will raise a 500 error: 
``` 
Error: INTERNAL SERVER ERROR
{
"detail": "'NoneType' object has no attribute 'n_submissions'",
"status": 500,
"title": "Internal error"
}
```

**Comment by tschaffter** [comment]
@rrchai Please try again now that the project has been update to schemas 0.1.6.

**Comment by tschaffter** [comment]
### Update

`ChallengeResults` has been put aside for now and was not part of the review that led to schema 0.1.6.

**Comment by tschaffter** [comment]
This issue is deprecated
