### ISSUE TITLE
Create wireframe for the User Profile page

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/rocc-app#91]
Create a wireframe that represent the profile page of a ROCC user (lucid chart, figma, slide).

This page should provide information about the user and challenge activity.

**Comment by vpchung** [comment]
[Figma wireframe](https://www.figma.com/file/iclSaLjoDWOh6pnZxORESR/User-Profile) -- if you play the prototype, the buttons will navigate between the two pages.

**Comment by tschaffter** [comment]
@vpchung Next steps would be:

- Create an ng component and connect it to a route (@tschaffter )
- Develop the User page based on the wireframe (@rrchai or @vpchung )

**Comment by vpchung** [comment]
@tschaffter @rrchai Let me finalize the design based on feedback and our use cases, and then I will hand it off to y'all to develop.

(Or, if you prefer Rong, I can develop this page as well)
